MAX_LEN = 475
PRED_BATCH_SIZE = 8

N_SAMPLES_PER_AL_ITER = 30
MAX_SAMPLES_NUMBER = 30
AL_STRATEGY = "mnlp"
MNLP_SCORE_POSITIVES = True

N_EPOCHS = 4
BATCH_SIZE = 2
GRAD_ACCUM_STEPS = 2
LEARNING_RATE = 5e-5
VALIDATION_RATIO = 0.01
PATIENCE = 1

BERT_MODEL_TYPE = "distilbert-base-cased"
CACHE_DIR = "/notebook/models/cache"

RANDOM_STATE = 42

UPSAMPLE_POSITIVE = 1024
IS_SYNC = False

SUBSAMPLE = 0.1
AUTOFILL_SIMILAR = True

CONLL_MODE = True
